[versions]
##############################
# Supplied by New Project template
##############################

agp = "8.13.2"
kotlin = "2.3.0"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.10.0"
activityCompose = "1.12.2"
composeBom = "2025.12.01"

##############################
# Added by Codepunk
##############################

# See https://github.com/google/ksp/releases
# to find which ksp version works with with which version of kotlin
ksp = "2.2.21-2.0.4"

arrow = "2.2.1.1"
coil = "3.3.0"
datastore = "1.2.0"
datetime = "0.7.1"
desugar = "2.1.5"
fonts = "1.10.0"
hilt = "2.57.2"
hiltNavigationCompose = "1.3.0"
javapoet = "1.13.0"
jsoup = "1.22.1"
lifecycle = "2.10.0"
material3Adaptive = "1.4.0"
navigation = "2.9.6"
paging = "3.3.6"
ph-css = "8.1.1"
retrofit = "3.0.0"
room = "2.8.4"
serialization = "1.9.0"
splashscreen = "1.2.0"
timber = "5.0.1"

[libraries]
##############################
# Supplied by New Project template
##############################

androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }

##############################
# Added by Codepunk
##############################

# Android Gradle Plugin
android-gradle-plugin = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }

# Arrow
arrow-core = { group = "io.arrow-kt", name = "arrow-core", version.ref = "arrow" }
arrow-fx-coroutines = { group = "io.arrow-kt", name = "arrow-fx-coroutines", version.ref = "arrow" }
arrow-core-retrofit = { group = "io.arrow-kt", name = "arrow-core-retrofit", version.ref = "arrow" }

# Coil
coil-compose = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil" }
coil-network = { group = "io.coil-kt.coil3", name = "coil-network-okhttp", version.ref = "coil" }

# Datastore (Preferences)
datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }

# Datastore (Proto)
datastore-proto = { group = "androidx.datastore", name = "datastore", version.ref = "datastore" }

# Datetime
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "datetime" }

# Desugar (for using java.time APIs on older Android versions)
desugar-jdk-libs = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "desugar" }

# Google Fonts
google-fonts = { group = "androidx.compose.ui", name = "ui-text-google-fonts", version.ref = "fonts" }

# Hilt Android Library
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltNavigationCompose" }

# JavaPoet (needed due to an artifact introduced when using Hilt)
javapoet = { group = "com.squareup", name = "javapoet", version.ref = "javapoet" }

# Jsoup & PH-CSS (for parsing & scraping HTML & CSS files)
jsoup = { group = "org.jsoup", name = "jsoup", version.ref = "jsoup" }
ph-css = { group = "com.helger", name = "ph-css", version.ref = "ph-css" }

# Kotlin Gradle Plugin
# kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kgp" }

# Lifecycle
lifecycle-process = { group = "androidx.lifecycle", name = "lifecycle-process", version.ref = "lifecycle" }

# Material3 Adaptive
# material3-adaptive = { group = "androidx.compose.material3.adaptive", name = "adaptive", version.ref = "material3Adaptive" }
# material3-adaptive-layout = { group = "androidx.compose.material3.adaptive", name = "adaptive-layout", version.ref = "material3Adaptive" }
# material3-adaptive-navigation = { group = "androidx.compose.material3.adaptive", name = "adaptive-navigation", version.ref = "material3Adaptive" }
material3-adaptive-navigation-suite = { group = "androidx.compose.material3", name = "material3-adaptive-navigation-suite", version.ref = "material3Adaptive" }

# Compose integration with Navigation
navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation" }

# Paging
paging-runtime = { group = "androidx.paging", name = "paging-runtime", version.ref = "paging" }
paging-compose = { group = "androidx.paging", name = "paging-compose", version.ref = "paging" }

# Retrofit
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-serialization = { group = "com.squareup.retrofit2", name = "converter-kotlinx-serialization", version.ref = "retrofit" }

# Room
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-testing = { group = "androidx.room", name = "room-testing", version.ref = "room" }
room-paging = { group = "androidx.room", name = "room-paging", version.ref = "room" }

# Kotlin serialization runtime library
serialization = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serialization" }

# Splash screen
splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "splashscreen" }

# Timber
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }

[plugins]
##############################
# Supplied by New Project template
##############################

kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

##############################
# Added by Codepunk
##############################

# Hilt Gradle Plugin
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }

# Kotlin Symbol Processing (KSP) API
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

# Room
room = { id = "androidx.room", version.ref = "room" }

# Kotlin serialization
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
